import { Router } from "express";
import { authRoutes } from "./modules/auth/auth.routes.js";
import { customerRoutes } from "./modules/customers/customer.routes.js";
import { categoryRoutes } from "./modules/categories/category.routes.js";
import { brandRoutes } from "./modules/brands/brand.routes.js";
import { productRoutes } from "./modules/products/product.routes.js";
import { productVariationRoutes } from "./modules/productVariations/productVariation.routes.js";
import { dashboardRoutes } from "./modules/dashboard/dashboard.routes.js";
import { saleRoutes } from "./modules/sales/sale.routes.js";
import { invoiceRoutes } from "./modules/invoices/invoice.routes.js";
import { stockMovementRoutes } from "./modules/stockMovements/stockMovement.routes.js";
import { reportsRoutes } from "./modules/reports/reports.routes.js";
import { crediarioRoutes } from "./modules/crediario/crediario.routes.js";
import { supplierRoutes } from "./modules/suppliers/supplier.routes.js";
import { nfeImportRoutes } from "./modules/nfeImports/nfeImport.routes.js";
import { billingRoutes } from "./modules/billing/billing.routes.js";
import { userRoutes } from "./modules/users/user.routes.js";
import { cashRoutes } from "./modules/cash/cash.routes.js";
import { stockAlertRoutes } from "./modules/stockAlerts/stockAlert.routes.js";

const router = Router();

router.get("/health", (_req, res) => res.json({ ok: true }));
router.use("/auth", authRoutes);
router.use("/billing", billingRoutes);
router.use("/users", userRoutes);
router.use("/customers", customerRoutes);
router.use("/categories", categoryRoutes);
router.use("/brands", brandRoutes);
router.use("/products", productRoutes);
router.use("/product-variations", productVariationRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/sales", saleRoutes);
router.use("/invoices", invoiceRoutes);
router.use("/stock-movements", stockMovementRoutes);
router.use("/reports", reportsRoutes);
router.use("/crediario", crediarioRoutes);
router.use("/suppliers", supplierRoutes);
router.use("/nfe-imports", nfeImportRoutes);
router.use("/cash", cashRoutes);
router.use("/stock-alerts", stockAlertRoutes);

export { router };
